# Generated by Django 6.0.3 on 2026-03-06 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parentinput',
            old_name='milestones',
            new_name='form_data',
        ),
        migrations.RemoveField(
            model_name='parentinput',
            name='areas_of_concern',
        ),
        migrations.RemoveField(
            model_name='parentinput',
            name='behaviors',
        ),
        migrations.RemoveField(
            model_name='parentinput',
            name='home_support_routines',
        ),
        migrations.RemoveField(
            model_name='parentinput',
            name='medical_info',
        ),
        migrations.RemoveField(
            model_name='parentinput',
            name='parent_goals',
        ),
        migrations.RemoveField(
            model_name='parentinput',
            name='sensory_needs',
        ),
        migrations.RemoveField(
            model_name='parentinput',
            name='social_skills',
        ),
    ]
