# Generated by Django 6.0.3 on 2026-03-06 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_milestones_parentinput_form_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='status',
            field=models.CharField(choices=[('PENDING_ASSESSMENT', 'Pending Assessment'), ('ASSESSMENT_SCHEDULED', 'Assessment Scheduled'), ('ASSESSED', 'Assessed'), ('ENROLLED', 'Enrolled')], default='PENDING_ASSESSMENT', max_length=30),
        ),
    ]
