# Generated by Django 6.0.3 on 2026-03-06 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_student_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specialistinputa',
            name='academic_skill',
        ),
        migrations.RemoveField(
            model_name='specialistinputa',
            name='adhd_checklist',
        ),
        migrations.RemoveField(
            model_name='specialistinputa',
            name='areas_of_concern',
        ),
        migrations.RemoveField(
            model_name='specialistinputa',
            name='asd_checklist',
        ),
        migrations.RemoveField(
            model_name='specialistinputa',
            name='behavior_skill',
        ),
        migrations.RemoveField(
            model_name='specialistinputa',
            name='communication_skill',
        ),
        migrations.RemoveField(
            model_name='specialistinputa',
            name='delayed_speech_checklist',
        ),
        migrations.RemoveField(
            model_name='specialistinputa',
            name='dyslexia_checklist',
        ),
        migrations.RemoveField(
            model_name='specialistinputa',
            name='motor_skill',
        ),
        migrations.RemoveField(
            model_name='specialistinputa',
            name='strengths',
        ),
        migrations.RemoveField(
            model_name='specialistinputb',
            name='goals_progress',
        ),
        migrations.RemoveField(
            model_name='specialistinputb',
            name='improvements',
        ),
        migrations.RemoveField(
            model_name='specialistinputb',
            name='sessions_attended',
        ),
        migrations.RemoveField(
            model_name='specialistinputb',
            name='strengths',
        ),
        migrations.RemoveField(
            model_name='specialistinputb',
            name='therapy_type',
        ),
        migrations.RemoveField(
            model_name='teacherinput',
            name='arts',
        ),
        migrations.RemoveField(
            model_name='teacherinput',
            name='behavior',
        ),
        migrations.RemoveField(
            model_name='teacherinput',
            name='english',
        ),
        migrations.RemoveField(
            model_name='teacherinput',
            name='math',
        ),
        migrations.RemoveField(
            model_name='teacherinput',
            name='prewriting',
        ),
        migrations.RemoveField(
            model_name='teacherinput',
            name='science',
        ),
        migrations.RemoveField(
            model_name='teacherinput',
            name='sessions_attended',
        ),
        migrations.AddField(
            model_name='specialistinputa',
            name='form_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='specialistinputb',
            name='form_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='teacherinput',
            name='form_data',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
