# Generated by Django 6.0.3 on 2026-03-09 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_specialistinputa_academic_skill_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='status',
            field=models.CharField(choices=[('PENDING_ASSESSMENT', 'Pending Assessment'), ('ASSESSMENT_REQUESTED', 'Assessment Requested'), ('ASSESSMENT_SCHEDULED', 'Assessment Scheduled'), ('ASSESSED', 'Assessed'), ('ENROLLED', 'Enrolled')], default='PENDING_ASSESSMENT', max_length=30),
        ),
    ]
