# Generated by Django 6.0.3 on 2026-03-09 22:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_student_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specialistinputa',
            name='report_cycle',
        ),
        migrations.RemoveField(
            model_name='specialistinputa',
            name='student',
        ),
        migrations.RemoveField(
            model_name='specialistinputa',
            name='submitted_by',
        ),
        migrations.RemoveField(
            model_name='specialistinputb',
            name='report_cycle',
        ),
        migrations.RemoveField(
            model_name='specialistinputb',
            name='student',
        ),
        migrations.RemoveField(
            model_name='specialistinputb',
            name='submitted_by',
        ),
        migrations.RemoveField(
            model_name='teacherinput',
            name='report_cycle',
        ),
        migrations.RemoveField(
            model_name='teacherinput',
            name='student',
        ),
        migrations.RemoveField(
            model_name='teacherinput',
            name='submitted_by',
        ),
        migrations.CreateModel(
            name='MultidisciplinaryAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('report_cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.reportcycle')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.student')),
                ('submitted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MultidisciplinaryProgressTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('report_cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.reportcycle')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.student')),
                ('submitted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ParentAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('report_cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.reportcycle')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.student')),
                ('submitted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ParentProgressTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('report_cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.reportcycle')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.student')),
                ('submitted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SpedAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('report_cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.reportcycle')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.student')),
                ('submitted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SpedProgressTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('report_cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.reportcycle')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.student')),
                ('submitted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='ParentInput',
        ),
        migrations.DeleteModel(
            name='SpecialistInputA',
        ),
        migrations.DeleteModel(
            name='SpecialistInputB',
        ),
        migrations.DeleteModel(
            name='TeacherInput',
        ),
    ]
