# Generated by Django 6.0.3 on 2026-03-10 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_invitation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='grade',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
