# Generated by Django 6.0.3 on 2026-03-10 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_student_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='grade',
            field=models.CharField(default='TBD', max_length=50),
            preserve_default=False,
        ),
    ]
