# Generated by Django 6.0.3 on 2026-03-11 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_invitation_student_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='specialty',
            field=models.CharField(blank=True, default='', help_text='e.g. Speech Therapy, Occupational Therapy, Behavioral Therapy', max_length=100),
        ),
    ]
