# Generated by Django 6.0.3 on 2026-03-11 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_add_specialty_to_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='generateddocument',
            name='iep_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='generateddocument',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='generated_reports/'),
        ),
    ]
