# Generated by Django 6.0.3 on 2026-03-23 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_generateddocument_iep_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='generateddocument',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('FINAL', 'Final')], default='DRAFT', max_length=10),
        ),
    ]
