# Generated by Django 6.0.3 on 2026-03-27 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_documentversion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='status',
            field=models.CharField(choices=[('INQUIRY', 'Inquiry'), ('EVALUATION', 'Evaluation'), ('REVIEW', 'Review'), ('ACTIVE', 'Active'), ('ARCHIVED', 'Archived')], default='INQUIRY', max_length=30),
        ),
    ]
