# Generated by Django 6.0.3 on 2026-03-28 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_alter_student_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='status',
            field=models.CharField(choices=[('PENDING_ASSESSMENT', 'Pending Assessment'), ('ASSESSMENT_SCHEDULED', 'Assessment Scheduled'), ('OBSERVATION_PENDING', 'Observation Pending'), ('OBSERVATION_SCHEDULED', 'Observation Scheduled'), ('ASSESSED', 'Assessed'), ('ENROLLED', 'Enrolled'), ('ARCHIVED', 'Archived')], default='PENDING_ASSESSMENT', max_length=30),
        ),
    ]
