# Generated by Django 6.0.3 on 2026-04-01 16:22

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_alter_student_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='expires_at',
            field=models.DateTimeField(default=api.models.default_expiration),
        ),
    ]
