# Generated by Django 6.0.3 on 2026-04-05 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_user_is_phone_verified_phoneverification'),
    ]

    operations = [
        migrations.AddField(
            model_name='multidisciplinaryassessment',
            name='original_language',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='multidisciplinaryassessment',
            name='translated_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='multidisciplinaryprogresstracker',
            name='original_language',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='multidisciplinaryprogresstracker',
            name='translated_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='parentassessment',
            name='original_language',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='parentassessment',
            name='translated_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='parentprogresstracker',
            name='original_language',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='parentprogresstracker',
            name='translated_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='spedassessment',
            name='original_language',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='spedassessment',
            name='translated_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='spedprogresstracker',
            name='original_language',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='spedprogresstracker',
            name='translated_data',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
