# Generated by Django 6.0.3 on 2026-04-05 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_multidisciplinaryassessment_original_language_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generateddocument',
            name='document_type',
            field=models.CharField(choices=[('IEP', 'IEP'), ('ASSESSMENT', 'Assessment'), ('MONTHLY', 'Monthly Progress Report')], max_length=20),
        ),
    ]
