# Generated by Django 6.0.3 on 2026-04-05 14:00

from django.db import migrations


def convert_weekly_to_monthly(apps, schema_editor):
    GeneratedDocument = apps.get_model('api', 'GeneratedDocument')
    GeneratedDocument.objects.filter(document_type='WEEKLY').update(document_type='MONTHLY')

def reverse_conversion(apps, schema_editor):
    GeneratedDocument = apps.get_model('api', 'GeneratedDocument')
    GeneratedDocument.objects.filter(document_type='MONTHLY').update(document_type='WEEKLY')


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_alter_generateddocument_document_type'),
    ]

    operations = [
        migrations.RunPython(convert_weekly_to_monthly, reverse_conversion),
    ]
