# Generated by Django 6.0.3 on 2026-04-05 19:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_convert_weekly_to_monthly_docs'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportcycle',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reportcycle',
            name='label',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='reportcycle',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('GRACE', 'Grace Period'), ('GENERATING', 'Generating'), ('COMPLETED', 'Completed')], default='OPEN', max_length=20),
        ),
    ]
