# Generated by Django 6.0.3 on 2026-04-17 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_add_cycle_status_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='status',
            field=models.CharField(choices=[('PENDING_ASSESSMENT', 'Pending Assessment'), ('ASSESSMENT_SCHEDULED', 'Assessment Scheduled'), ('ASSESSED', 'Assessed'), ('ENROLLED', 'Enrolled'), ('ARCHIVED', 'Archived')], default='PENDING_ASSESSMENT', max_length=30),
        ),
    ]
