# Generated by Django 6.0.3 on 2026-04-17 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='link',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='notification',
            name='message',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('FORM_SUBMITTED', 'Form Submitted'), ('STUDENT_ENROLLED', 'Student Enrolled'), ('STUDENT_ASSESSED', 'Student Assessed'), ('IEP_GENERATED', 'IEP Generated'), ('REPORT_GENERATED', 'Report Generated'), ('REPORT_FINALIZED', 'Report Finalized'), ('SPECIALIST_ASSIGNED', 'Specialist Assigned'), ('TEACHER_ASSIGNED', 'Teacher Assigned'), ('CYCLE_CREATED', 'Cycle Created'), ('REMINDER', 'Reminder'), ('SYSTEM', 'System')], max_length=30),
        ),
        migrations.AlterField(
            model_name='notification',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
