# Generated by Django 6.0.3 on 2026-04-21 06:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_normalize_specialist_specialties'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialistPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialty', models.CharField(max_length=100)),
                ('specialist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specialist_preferences', to='api.student')),
            ],
            options={
                'unique_together': {('student', 'specialty')},
            },
        ),
    ]
