# Generated by Django 6.0.3 on 2026-04-21 13:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_specialistpreference'),
    ]

    operations = [
        migrations.AddField(
            model_name='multidisciplinaryassessment',
            name='finalized_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='multidisciplinaryassessment',
            name='finalized_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finalized_multidisciplinary_assessments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='multidisciplinaryprogresstracker',
            name='finalized_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='multidisciplinaryprogresstracker',
            name='finalized_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finalized_multidisciplinary_trackers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='SectionContribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_type', models.CharField(choices=[('assessment', 'Multidisciplinary Assessment'), ('tracker', 'Multidisciplinary Progress Tracker')], max_length=20)),
                ('section_key', models.CharField(max_length=50)),
                ('specialty', models.CharField(blank=True, default='', max_length=100)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted')], default='draft', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('assessment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='section_contributions', to='api.multidisciplinaryassessment')),
                ('specialist', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('tracker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='section_contributions', to='api.multidisciplinaryprogresstracker')),
            ],
            options={
                'unique_together': {('assessment', 'section_key'), ('tracker', 'section_key')},
            },
        ),
    ]
