# Generated by Django 6.0.3 on 2026-04-21 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_multidisciplinaryassessment_finalized_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='specialties',
            field=models.JSONField(blank=True, default=list, help_text='All specialist disciplines this user holds. Source of truth for section ownership.'),
        ),
        migrations.AlterField(
            model_name='user',
            name='specialty',
            field=models.CharField(blank=True, default='', help_text='Primary specialist discipline (mirrors specialties[0] for legacy reads).', max_length=100),
        ),
    ]
