# Generated by Django 6.0.3 on 2026-04-25 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0039_assessmentappointment_specialist_set_null'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='actor_name',
            field=models.CharField(blank=True, default='', help_text='Display name of the user who triggered this notification.', max_length=200),
        ),
    ]
