# Generated by Django 6.0.3 on 2026-04-25 13:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0041_alter_user_managers_remove_user_username_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='status',
            field=models.CharField(choices=[('AWAITING_PARENT_INPUT', 'Awaiting Parent Input'), ('PENDING_ASSESSMENT', 'Pending Assessment'), ('ASSESSED', 'Assessed'), ('ENROLLED', 'Enrolled'), ('ARCHIVED', 'Archived')], default='AWAITING_PARENT_INPUT', max_length=30),
        ),
        migrations.CreateModel(
            name='DiagnosticReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='diagnostic_reports/')),
                ('original_filename', models.CharField(blank=True, default='', max_length=255)),
                ('extracted_text', models.TextField(blank=True, default='', help_text='AI-extracted text from the uploaded document.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnostic_reports', to='api.student')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
