# Generated by Codex on 2026-05-04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0043_alter_student_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='dedupe_key',
            field=models.CharField(blank=True, db_index=True, default='', max_length=255),
        ),
        migrations.AddConstraint(
            model_name='notification',
            constraint=models.UniqueConstraint(
                condition=~models.Q(dedupe_key=''),
                fields=('recipient', 'dedupe_key'),
                name='unique_notification_recipient_dedupe_key',
            ),
        ),
    ]
