# Generated by Django 6.0.3 on 2026-05-06 10:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0044_notification_dedupe_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('STUDENT_CREATED', 'Student Created'), ('STUDENT_UPDATED', 'Student Updated'), ('STUDENT_STATUS_CHANGED', 'Student Status Changed'), ('TEAM_UPDATED', 'Team Updated'), ('FORM_SUBMITTED', 'Form Submitted'), ('FORM_FINALIZED', 'Form Finalized'), ('REPORT_QUEUED', 'Report Queued'), ('REPORT_GENERATING', 'Report Generating'), ('REPORT_READY', 'Report Ready'), ('REPORT_FAILED', 'Report Failed'), ('REPORT_FINALIZED', 'Report Finalized'), ('SCHEDULE_UPDATED', 'Schedule Updated'), ('DIAGNOSTIC_UPLOADED', 'Diagnostic Uploaded'), ('USER_REGISTERED', 'User Registered'), ('ONBOARDING_COMPLETED', 'Onboarding Completed'), ('SYSTEM', 'System')], max_length=40)),
                ('visibility', models.CharField(choices=[('ADMINS', 'Admins'), ('STUDENT_TEAM', 'Student Team')], default='STUDENT_TEAM', max_length=20)),
                ('actor_name', models.CharField(blank=True, default='', max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField(blank=True, default='')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_events', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activity_events', to='api.student')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['visibility', '-created_at'], name='api_activit_visibil_f7b71d_idx'), models.Index(fields=['student', '-created_at'], name='api_activit_student_de27c5_idx'), models.Index(fields=['event_type', '-created_at'], name='api_activit_event_t_147f8e_idx')],
            },
        ),
    ]
