# Generated by Django 6.0.3 on 2026-05-29 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0045_activityevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='multidisciplinaryassessment',
            name='unlock_requested',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('FORM_SUBMITTED', 'Form Submitted'), ('STUDENT_ENROLLED', 'Student Enrolled'), ('STUDENT_ASSESSED', 'Student Assessed'), ('IEP_GENERATED', 'IEP Generated'), ('REPORT_GENERATED', 'Report Generated'), ('REPORT_FINALIZED', 'Report Finalized'), ('SPECIALIST_ASSIGNED', 'Specialist Assigned'), ('TEACHER_ASSIGNED', 'Teacher Assigned'), ('CYCLE_CREATED', 'Cycle Created'), ('REMINDER', 'Reminder'), ('UNLOCK_REQUESTED', 'Unlock Requested'), ('SYSTEM', 'System')], max_length=30),
        ),
    ]
