# Generated by Django 6.0.3 on 2026-06-10 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0047_parentassessment_unlock_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='multidisciplinaryprogresstracker',
            name='unlock_requested',
            field=models.BooleanField(default=False),
        ),
    ]
