# Generated by Django 6.0.3 on 2026-06-13 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0049_dedupe_and_unique_multidisciplinary_forms'),
    ]

    operations = [
        migrations.AddField(
            model_name='generateddocument',
            name='pdf_section_visibility',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
