# Generated by Django 6.0.3 on 2026-07-18 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0050_generateddocument_pdf_section_visibility'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='specialties',
            field=models.JSONField(blank=True, default=list, help_text='Specialist disciplines pre-assigned by admin, applied to the account on registration.'),
        ),
    ]
