# Generated by Django 6.0.3 on 2026-08-02 06:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0051_invitation_specialties'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialtyChangeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_specialties', models.JSONField(blank=True, default=list, help_text="Snapshot of the specialist's specialties when the request was raised.")),
                ('requested_specialties', models.JSONField(blank=True, default=list, help_text='Full set of specialties the specialist wants to end up with.')),
                ('note', models.TextField(blank=True, default='', help_text="Specialist's explanation for admin.")),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('admin_note', models.TextField(blank=True, default='', help_text="Admin's reply when approving or rejecting.")),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='specialty_change_reviews', to=settings.AUTH_USER_MODEL)),
                ('specialist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specialty_change_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'PENDING')), fields=('specialist',), name='unique_pending_specialty_change_request')],
            },
        ),
    ]
