# Generated by Django 6.0.3 on 2026-08-02 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0052_specialtychangerequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='grade_level',
            field=models.CharField(blank=True, default='', help_text='Grade level pre-assigned by admin, applied to the teacher account on registration.', max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='grade_level',
            field=models.CharField(blank=True, default='', help_text='The grade level a teacher handles. Assigned by admin, used for student matching.', max_length=50),
        ),
    ]
